title = "Sathashini"
baseURL = "https://example.com/"
theme = "my-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Ariyalur, India"
favicon = "/favicon.ico"
firstName = "Sathashini"
lastName = ""
phone = "1-555-555-1234"
showSocializations = true
showContact = false
sections = ["skills","publications","creations","contributions","experience","education","blog"]


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/sathashini-s-048943251"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/sathashini4623/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
